USE EXIF;
CREATE TABLE `USUARIOS` (
`ID` int unsigned NOT NULL AUTO_INCREMENT,
`NICK` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
`CLAVE` varchar(60) DEFAULT NULL,
`NOMAPE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
`LAT` decimal(11,5) DEFAULT NULL,
`LON` decimal(11,5) DEFAULT NULL,
`FOTO` longblob,
`CORREO` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
PRIMARY KEY (`ID`) USING BTREE,
UNIQUE KEY `IND_NICK` (`NICK`) USING BTREE,
UNIQUE KEY `IND_CORREO` (`CORREO`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;